openapi: 3.0.3
info:
  title: wookieBooks
  description: wookieBooks
  version: 1.0.0
servers:
  - url: https://server.com
    description: New server
  - url: 'https'
paths:
  /url:
    get:
      description: New endpoint
      responses:
        200:
          description: New response
          content:
            application/json:
              schema:
  
